#!/bin/bash

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# digiYo repo (webpages)
cd "$script_dir/"
git pull
git add .
git commit -m "Sullivan Myer"
git push
git pull
